namespace __Game__.Scripts.Gameplay
{
	public enum TargetProviderType
	{
		NONE = 0,
		UNIT_WEAPON = 1,
		UNIT_POSITION = 2,
		TARGET_POSITION = 3,
		RANDOM_POSITION = 4,
		FIRST_ENEMY = 50,
		RANDOM_ENEMY = 51,
		TARGET_HOLDER = 52,
		DAMAGE_SOURCE = 53,
		MULTISHOT_FIRST_ENEMY = 100,
		MULTISHOT_SECOND_RANDOM = 101,
		MULTISHOT_TARGET_HOLDER = 102,
		FORWARD_MOVEMENT = 200
	}
}
